CREATE TABLE "Students" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"NAME"	TEXT NOT NULL,
	"AGE"	INTEGER,
	"ADDRESS_CITY"	TEXT,
	"VIP"	TEXT DEFAULT 'no',
	"Class_ID"	INTEGER,
	FOREIGN KEY("Class_ID") REFERENCES "Class"("ID")
);

CREATE TABLE "Class" (
	"ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"NAME"	TEXTUMBER_ NOT NULL,
	"CODE"	INTEGER UNIQUE,
	"NUMBER_OF_STUDENTS"	INTEGER,
	"NUMBER_OF_VIP"	INTEGER,
	"AGE_AVERAGE"	INTEGER,
	"MOST_POPULAR_CITY"	TEXT,
	"OLDEST_VIP"	INTEGER,
	"YOUNGEST_VIP"	INTEGER
);

UPDATE Class SET NUMBER_OF_STUDENTS = (SELECT count (Class_ID) FROM Students WHERE Students.Class_ID = Class.ID);

UPDATE Class SET NUMBER_OF_VIP = (SELECT count (Class_ID) FROM Students WHERE Students.VIP = 'yes' AND Students.Class_ID = Class.ID);

UPDATE Class SET AGE_AVERAGE = (SELECT avg (AGE) FROM Students WHERE Students.Class_ID = Class.ID);

UPDATE Class SET MOST_POPULAR_CITY = (SELECT max (ADDRESS_CITY) FROM Students WHERE Students.Class_ID = Class.ID);

UPDATE Class SET OLDEST_VIP = (SELECT max (AGE) FROM Students WHERE Students.Class_ID = Class.ID);

UPDATE Class SET YOUNGEST_VIP = (SELECT min (AGE) FROM Students WHERE Students.Class_ID = Class.ID);
